version: "3.8"
services:
  alertmanager:
    container_name: alertmanager
    image: training-alertmanager
    build:
      context: ./services/alertmanager
    volumes:
    - ./config/alertmanager.yml:/root/alertmanager.yml
    - alertmanager-data:/root/data
    ports:
    - 9093:9093
  telegram-bot:
    container_name: telegram-bot
    image: wwmoraes/alertmanager-telegram-bot
    env_file:
    - ./services/telegram-bot/.env
    ports:
    - 8443:8443
  grafana:
    container_name: grafana
    image: training-grafana
    build:
      context: ./services/grafana
    volumes:
    - ./config/grafana:/root/conf
    - ./config/dashboards:/root/dashboards
    - grafana-data:/root/data
    ports:
    - 3000:3000
  blackbox:
    container_name: blackbox
    image: training-blackbox
    build:
      context: ./services/blackbox
    volumes:
    - ./config/blackbox.yml:/root/blackbox.yml
    ports:
    - 9115:9115
  prometheus:
    container_name: prometheus
    image: training-prometheus
    build:
      context: ./services/prometheus
    volumes:
    - ./config/prometheus.yml:/root/prometheus.yml
    - prometheus-data:/root/data
    ports:
    - 9090:9090
  node:
    container_name: node
    image: training-node
    build:
      context: ./services/node
    volumes:
    - ./services/node/app.py:/root/app.py
    ports:
    - 9100:9100
    - 8080:8080
  smtp:
    container_name: smtp
    image: camptocamp/smtp-sink
    restart: unless-stopped
    volumes:
      - mailbox-data:/home/smtp/Maildir/
  imap:
    container_name: imap
    image: camptocamp/courier-imap
    restart: unless-stopped
    volumes:
      - mailbox-data:/home/smtp/Maildir/
  webmail:
    container_name: webmail
    image: camptocamp/roundcube
    restart: unless-stopped
    environment:
      - IMAP_HOSTNAME=imap
      - SMTP_HOSTNAME=smtp
    ports:
      - "8181:80"
    volumes:
      - roundcube-data:/var/lib/dbconfig-common/sqlite3/roundcube

volumes:
  grafana-data: {}
  prometheus-data: {}
  alertmanager-data: {}
  roundcube-data: {}
  mailbox-data: {}
