{
 "title": "App",
 "description": "Testing metrics from the app",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency <= 5ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "vector(0.99)", "legendFormat": "target" },
    {
     "expr": " sum(rate(app_http_request_duration_seconds_bucket{le=\"0.005\"}[15m]))\n/\n  sum(rate(app_http_request_duration_seconds_count[15m]))",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(rate(app_http_request_duration_seconds_bucket{le=\"0.005\"}[1m]))\n/\n  sum(rate(app_http_request_duration_seconds_count[1m]))",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Request latency 90p",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(app_http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "1m"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "5m"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(app_http_request_duration_seconds_bucket[15m])))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "1m" },
    { "expr": "rate(app_requests_total[5m])", "legendFormat": "5m" },
    { "expr": "rate(app_requests_total[15m])", "legendFormat": "15m" }
   ]
  },
  {
   "title": "latency 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(app_http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.8, sum by (le)(rate(app_http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "80p"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(app_http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Request latency (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_seconds_sum[1m]))/sum(rate(app_http_request_duration_seconds_count[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "sum(rate(app_http_request_duration_seconds_sum[5m]))/sum(rate(app_http_request_duration_seconds_count[5m]))",
     "legendFormat": "5m"
    },
    {
     "expr": "sum(rate(app_http_request_duration_seconds_sum[15m]))/sum(rate(app_http_request_duration_seconds_count[15m]))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "time() - app_requests_created" }
   ]
  },
  {
   "title": "reqps 1m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "rate(app_requests_total[1m])" }
   ]
  }
 ]
}