{
 "title": "Load",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(up,instance)" },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "System Load 1m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_load15{instance=~\"${instance:pipe}\"}) by (instance) / count by (instance) (node_cpu_seconds_total{instance=~\"${instance:pipe}\",mode=\"idle\"})",
     "legendFormat": "{{instance}} 1m"
    }
   ]
  },
  {
   "title": "System Load 5m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"${instance:pipe}\"}) by (instance)",
     "legendFormat": "{{instance}} 5m"
    }
   ]
  },
  {
   "title": "System Load 15m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"${instance:pipe}\"}) by (instance)",
     "legendFormat": "{{instance}} 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance)((node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) / sum by (instance)(rate(node_cpu_seconds_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}