global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'general'
receivers:
- name: 'general'
  email_configs:
  - send_resolved: True
    to: engineer@localhost
    from: monitorning@localhost
    smarthost: smtp:25
    require_tls: False
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
